/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module changebit_rtl(i_argA, i_argB, o_result, error);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  output error;
  input [3:0] i_argA;
  input [3:0] i_argB;
  output [3:0] o_result;
  assign _00_ = ~i_argB[3];
  assign _01_ = ~i_argB[2];
  assign error = i_argB[3] | i_argB[2];
  assign _02_ = i_argB[3] | i_argB[0];
  assign _03_ = ~_02_;
  assign _04_ = i_argB[2] | i_argB[1];
  assign _05_ = ~_04_;
  assign _06_ = _02_ | _04_;
  assign _07_ = ~_06_;
  assign o_result[0] = i_argA[0] | _07_;
  assign _08_ = _00_ & i_argB[0];
  assign _09_ = _05_ & _08_;
  assign o_result[1] = i_argA[1] | _09_;
  assign _10_ = _01_ & i_argB[1];
  assign _11_ = _03_ & _10_;
  assign o_result[2] = i_argA[2] | _11_;
  assign _12_ = _08_ & _10_;
  assign o_result[3] = i_argA[3] | _12_;
endmodule
